Order front
Retro-R-Us/Retro-R-Us pull request #114
Opened 2023-01-23 01:45 UTC by jhoolwerf

Closes #67 
Closes #99

2023-01-23 02:21 UTC, Remics89 requested changes

2023-01-23 02:21 UTC, Remics89 commented on src/api/orders.js
> +                orderId: orderId,
orderId key is fine, but the value orderId isn't an argument. The same goes for line 38 where orderId isn't defined. You'll have to change the argument "id to orderId"

2023-01-23 03:11 UTC, Remics89 approved these changes

2023-01-23 03:13 UTC, KayPaint approved these changes

2023-01-25 00:35 UTC, MShiers7 approved these changes

2023-01-25 00:53 UTC, merged