feat:Created Confirmation Page component
Retro-R-Us/Retro-R-Us pull request #127
Opened 2023-01-25 01:43 UTC by jhoolwerf

2023-01-26 01:31 UTC, MShiers7 approved these changes

2023-01-26 01:36 UTC, KayPaint approved these changes

2023-01-26 01:40 UTC, Remics89 approved these changes, later dismissed

2023-01-26 01:55 UTC, MShiers7 requested changes
needs a lowercase l after k on line 28

2023-01-26 08:27 UTC, Remics89 commented
> 
nice catch! it is indeed missing a lowercase L

2023-01-26 23:18 UTC, Remics89 approved these changes

2023-01-27 00:16 UTC, MShiers7 approved these changes

2023-01-27 00:48 UTC, merged