feat(db):Completed updateCart and getOrderById functions
Retro-R-Us/Retro-R-Us pull request #43
Opened 2023-01-07 17:20 UTC by jhoolwerf

2023-01-07 18:31 UTC, KayPaint approved these changes

2023-01-07 21:09 UTC, Remics89 commented on db/models/cart.js
> +        INSERT INTO cart("orderId", quantity)
we can add orderId and quantity but the cart table definition has to reflect that.

2023-01-07 21:25 UTC, Remics89 requested changes

2023-01-07 21:25 UTC, Remics89 commented on db/models/cart.js
> +        const fields = {};
fields here is undefined. Then at line 40, fields is called to create the setString. In this scenario, setString will always be undefined and hit your return at 44.

2023-01-07 21:25 UTC, Remics89 commented on db/models/cart.js
> +const client = require("./client");
- require client statement should have 2 dots to reference a file outside the immediate directory.

2023-01-07 21:37 UTC, Remics89 commented on db/models/cart.js
> +const client = require("./client");
```suggestion
const client = require("../client");
```

2023-01-07 21:38 UTC, Remics89 commented on db/models/cart.js
> +        const fields = {};
line 33 function arguments:
```suggestion
        {id, ...fields}
```

2023-01-09 01:58 UTC, Remics89 approved these changes

2023-01-09 01:59 UTC, merged