Collectibles db methods
Retro-R-Us/Retro-R-Us pull request #44
Opened 2023-01-07 18:19 UTC by MShiers7

2023-01-07 21:36 UTC, Remics89 requested changes

2023-01-07 21:36 UTC, Remics89 commented on db/models/collectibles.js
> +const client = require("./client");
require client statement should have 2 dots to reference a file outside the immediate directory.

2023-01-07 21:36 UTC, Remics89 commented on db/models/collectibles.js
> +const client = require("./client");
```suggestion
const client = require("../client");
```

2023-01-08 00:58 UTC, Remics89 approved these changes

2023-01-08 01:59 UTC, jhoolwerf approved these changes

2023-01-08 02:04 UTC, merged