feat(api):Developed Cart API
Retro-R-Us/Retro-R-Us pull request #54
Opened 2023-01-10 00:15 UTC by jhoolwerf

2023-01-10 00:19 UTC, MShiers7 approved these changes

2023-01-10 03:28 UTC, Remics89 requested changes

2023-01-10 03:28 UTC, Remics89 commented on api/cart.js
> +        const newOrder = await addItemToCart ({ orderId, quantity });
- Now that you have `{ Cart }` deconstructed on Line 3, youll want to call the db method as an object key/value:

```suggestion
        const newOrder = await Cart.addItemToCart ({ orderId, quantity });
```

2023-01-10 03:28 UTC, Remics89 commented on api/cart.js
> +            const deletedCart = await destroyCart(cartId);
- The same for here and for line 19.
- For line 19, be careful of the fact that getOrderById is a db method for Orders, not Cart.
```suggestion
            const deletedCart = await Cart.destroyCart(cartId);
```

2023-01-10 03:28 UTC, Remics89 commented on api/cart.js
> +            const updatedCart = await updateCart(cartId);
- This one as well as line 34
- For line 34, be careful of the fact that getOrderById is a db method for Orders, not Cart.

```suggestion
            const updatedCart = await Cart.updateCart(cartId);
```

2023-01-10 03:28 UTC, Remics89 commented on api/index.js
> +Router.use("/cart", cartRouter);
Youll want to reference apiRouter here.

```suggestion
apiRouter.use("/cart", cartRouter);
```

2023-01-11 01:14 UTC, Remics89 approved these changes

2023-01-11 01:20 UTC, merged